// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteUsersById, getUsers, getUsersById, type Options, postUsers, postUsersByIdResetPassword, putUsersById } from '../sdk.gen';
import type { DeleteUsersByIdData, DeleteUsersByIdError, DeleteUsersByIdResponse, GetUsersByIdData, GetUsersByIdError, GetUsersByIdResponse, GetUsersData, GetUsersError, GetUsersResponse, PostUsersByIdResetPasswordData, PostUsersByIdResetPasswordError, PostUsersByIdResetPasswordResponse, PostUsersData, PostUsersError, PostUsersResponse, PutUsersByIdData, PutUsersByIdError, PutUsersByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Retrieves a paginated list of users.
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, GetUsersError, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getUsersInfiniteQueryKey = (options?: Options<GetUsersData>): QueryKey<Options<GetUsersData>> => createQueryKey('getUsers', options, true);

/**
 * Retrieves a paginated list of users.
 */
export const getUsersInfiniteOptions = (options?: Options<GetUsersData>) => infiniteQueryOptions<GetUsersResponse, GetUsersError, InfiniteData<GetUsersResponse>, QueryKey<Options<GetUsersData>>, number | string | Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUsers({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersInfiniteQueryKey(options)
});

/**
 * Creates a new user.
 */
export const postUsersMutation = (options?: Partial<Options<PostUsersData>>): UseMutationOptions<PostUsersResponse, PostUsersError, Options<PostUsersData>> => {
    const mutationOptions: UseMutationOptions<PostUsersResponse, PostUsersError, Options<PostUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Deletes a user by their ID.
 */
export const deleteUsersByIdMutation = (options?: Partial<Options<DeleteUsersByIdData>>): UseMutationOptions<DeleteUsersByIdResponse, DeleteUsersByIdError, Options<DeleteUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteUsersByIdResponse, DeleteUsersByIdError, Options<DeleteUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersByIdQueryKey = (options: Options<GetUsersByIdData>) => createQueryKey('getUsersById', options);

/**
 * Retrieves a user by their ID.
 */
export const getUsersByIdOptions = (options: Options<GetUsersByIdData>) => queryOptions<GetUsersByIdResponse, GetUsersByIdError, GetUsersByIdResponse, ReturnType<typeof getUsersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsersById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersByIdQueryKey(options)
});

/**
 * Updates a user's information.
 */
export const putUsersByIdMutation = (options?: Partial<Options<PutUsersByIdData>>): UseMutationOptions<PutUsersByIdResponse, PutUsersByIdError, Options<PutUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<PutUsersByIdResponse, PutUsersByIdError, Options<PutUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Resets the password of a user by their ID.
 */
export const postUsersByIdResetPasswordMutation = (options?: Partial<Options<PostUsersByIdResetPasswordData>>): UseMutationOptions<PostUsersByIdResetPasswordResponse, PostUsersByIdResetPasswordError, Options<PostUsersByIdResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<PostUsersByIdResetPasswordResponse, PostUsersByIdResetPasswordError, Options<PostUsersByIdResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUsersByIdResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
