// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5211/' | (string & {});
};

/**
 * Represents the request to create a new user.
 */
export type CreateUserRequestDto = {
    /**
     * Gets or sets the username of the user.
     */
    username: string;
    /**
     * Gets or sets the first name of the user.
     */
    firstName: string;
    /**
     * Gets or sets the last name of the user.
     */
    lastName: string;
    /**
     * Gets or sets the group of the user.
     */
    group?: string;
    /**
     * Gets or sets the email address of the user.
     */
    email: null | string;
};

/**
 * Represents a paginated result containing a collection of items and pagination metadata.
 */
export type PagedResultDtoOfUserDto = {
    /**
     * Gets the read-only collection of items for the current page.
     */
    items?: null | Array<UserDto>;
    /**
     * Gets the current page number.
     */
    page: number | string;
    /**
     * Gets the number of items per page.
     */
    pageSize: number | string;
    /**
     * Gets the total number of items across all pages.
     */
    totalCount: number | string;
    /**
     * Gets the total number of pages, calculated based on the total count and page size.
     */
    totalPages?: number | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

/**
 * Represents the request to update the user information.
 */
export type UpdateUserRequestDto = {
    /**
     * Gets or sets the username of the user.
     */
    username: string;
    /**
     * Gets or sets the first name of the user.
     */
    firstName: string;
    /**
     * Gets or sets the last name of the user.
     */
    lastName: string;
    /**
     * Gets or sets the group of the user.
     */
    group?: string;
    /**
     * Gets or sets the email address of the user.
     */
    email: null | string;
};

/**
 * Represents a user data transfer object for Keycloak interactions.
 */
export type UserDto = {
    /**
     * Gets or sets the unique identifier of the user in Keycloak.
     */
    id: number | string;
    /**
     * Gets or sets the username of the user.
     */
    username: string;
    /**
     * Gets or sets the first name of the user.
     */
    firstName: string;
    /**
     * Gets or sets the last name of the user.
     */
    lastName: string;
    /**
     * Gets or sets the group of the user.
     */
    group: string;
    /**
     * Gets or sets the email address of the user.
     */
    email: null | string;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The page number (default is 1).
         */
        page?: number | string;
        /**
         * The number of items per page (default is 10).
         */
        pageSize?: number | string;
        /**
         * An optional list of group filters to apply when retrieving users.
         */
        group?: Array<string>;
        /**
         * An optional username filter to apply when retrieving users.
         */
        username?: string;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Invalid pagination parameters.
     */
    400: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Returns the paginated list of users.
     */
    200: PagedResultDtoOfUserDto;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    /**
     * The cancellation token.
     */
    body: CreateUserRequestDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Invalid user information provided.
     */
    400: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * Returns the created user details.
     */
    201: UserDto;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        id: number | string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUsersByIdErrors = {
    /**
     * User not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type DeleteUsersByIdError = DeleteUsersByIdErrors[keyof DeleteUsersByIdErrors];

export type DeleteUsersByIdResponses = {
    /**
     * User deleted successfully.
     */
    204: void;
};

export type DeleteUsersByIdResponse = DeleteUsersByIdResponses[keyof DeleteUsersByIdResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        id: number | string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * User not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * Returns the user details.
     */
    200: UserDto;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PutUsersByIdData = {
    /**
     * The cancellation token.
     */
    body: UpdateUserRequestDto;
    path: {
        /**
         * The unique identifier of the user.
         */
        id: number | string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdErrors = {
    /**
     * Invalid user information provided.
     */
    400: ProblemDetails;
    /**
     * User not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type PutUsersByIdError = PutUsersByIdErrors[keyof PutUsersByIdErrors];

export type PutUsersByIdResponses = {
    /**
     * Returns the updated user details.
     */
    200: UserDto;
};

export type PutUsersByIdResponse = PutUsersByIdResponses[keyof PutUsersByIdResponses];

export type PostUsersByIdResetPasswordData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        id: number | string;
    };
    query?: never;
    url: '/users/{id}/reset-password';
};

export type PostUsersByIdResetPasswordErrors = {
    /**
     * User not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server error occurred.
     */
    500: ProblemDetails;
};

export type PostUsersByIdResetPasswordError = PostUsersByIdResetPasswordErrors[keyof PostUsersByIdResetPasswordErrors];

export type PostUsersByIdResetPasswordResponses = {
    /**
     * Password reset successfully.
     */
    204: void;
};

export type PostUsersByIdResetPasswordResponse = PostUsersByIdResetPasswordResponses[keyof PostUsersByIdResetPasswordResponses];
